# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Nick Buckets
# Description of the Site
description: Crime fiction
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: Crime fiction, Writing
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/background_home_city.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: info@nickbuckets.com
facebook_username: NBucketsAuthor
twitter_username: NBucketsAuthor
instagram_username: NBucketsAuthor

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Nick Buckets
# URL for the Image of the Author
author-image: /assets/images/author_logo.jpg
# 60 Words About the Author
author-about: Crime fiction writer. Author of the book "Bad Seeds".
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://nickbuckets.com

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
